//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.MVC.FabricacionServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_PR_SolicitudProduccion", Namespace="http://schemas.datacontract.org/2004/07/ETNA.Domain")]
    [System.SerializableAttribute()]
    public partial class TB_PR_SolicitudProduccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantMaquinariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoSolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecSolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_MotivoRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsSolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitanteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolicitudProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantInsumos {
            get {
                return this.CantInsumosField;
            }
            set {
                if ((this.CantInsumosField.Equals(value) != true)) {
                    this.CantInsumosField = value;
                    this.RaisePropertyChanged("CantInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantMaquinaria {
            get {
                return this.CantMaquinariaField;
            }
            set {
                if ((this.CantMaquinariaField.Equals(value) != true)) {
                    this.CantMaquinariaField = value;
                    this.RaisePropertyChanged("CantMaquinaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantPersonal {
            get {
                return this.CantPersonalField;
            }
            set {
                if ((this.CantPersonalField.Equals(value) != true)) {
                    this.CantPersonalField = value;
                    this.RaisePropertyChanged("CantPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoSol {
            get {
                return this.EstadoSolField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSolField, value) != true)) {
                    this.EstadoSolField = value;
                    this.RaisePropertyChanged("EstadoSol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecSol {
            get {
                return this.FecSolField;
            }
            set {
                if ((this.FecSolField.Equals(value) != true)) {
                    this.FecSolField = value;
                    this.RaisePropertyChanged("FecSol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Glosa {
            get {
                return this.GlosaField;
            }
            set {
                if ((object.ReferenceEquals(this.GlosaField, value) != true)) {
                    this.GlosaField = value;
                    this.RaisePropertyChanged("Glosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_MotivoRechazo {
            get {
                return this.Id_MotivoRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_MotivoRechazoField, value) != true)) {
                    this.Id_MotivoRechazoField = value;
                    this.RaisePropertyChanged("Id_MotivoRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObsSol {
            get {
                return this.ObsSolField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsSolField, value) != true)) {
                    this.ObsSolField = value;
                    this.RaisePropertyChanged("ObsSol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanId {
            get {
                return this.PlanIdField;
            }
            set {
                if ((this.PlanIdField.Equals(value) != true)) {
                    this.PlanIdField = value;
                    this.RaisePropertyChanged("PlanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableId {
            get {
                return this.ResponsableIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableIdField, value) != true)) {
                    this.ResponsableIdField = value;
                    this.RaisePropertyChanged("ResponsableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SolicitanteId {
            get {
                return this.SolicitanteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitanteIdField, value) != true)) {
                    this.SolicitanteIdField = value;
                    this.RaisePropertyChanged("SolicitanteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SolicitudProdId {
            get {
                return this.SolicitudProdIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudProdIdField, value) != true)) {
                    this.SolicitudProdIdField = value;
                    this.RaisePropertyChanged("SolicitudProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorId {
            get {
                return this.SupervisorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorIdField, value) != true)) {
                    this.SupervisorIdField = value;
                    this.RaisePropertyChanged("SupervisorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoteDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.FB")]
    [System.SerializableAttribute()]
    public partial class LoteDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionTipoLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroLoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoLote {
            get {
                return this.DescripcionTipoLoteField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionTipoLoteField, value) != true)) {
                    this.DescripcionTipoLoteField = value;
                    this.RaisePropertyChanged("DescripcionTipoLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroLote {
            get {
                return this.NroLoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NroLoteField, value) != true)) {
                    this.NroLoteField = value;
                    this.RaisePropertyChanged("NroLote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FabricacionServices.IFabricacionService")]
    public interface IFabricacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/TB_PR_SolicitudProduccion_Listar", ReplyAction="http://tempuri.org/IFabricacionService/TB_PR_SolicitudProduccion_ListarResponse")]
        ETNA.MVC.FabricacionServices.TB_PR_SolicitudProduccion[] TB_PR_SolicitudProduccion_Listar(string pCOD_ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/TB_PR_SolicitudProduccion_Listar", ReplyAction="http://tempuri.org/IFabricacionService/TB_PR_SolicitudProduccion_ListarResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FabricacionServices.TB_PR_SolicitudProduccion[]> TB_PR_SolicitudProduccion_ListarAsync(string pCOD_ESTADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/InsertarLote", ReplyAction="http://tempuri.org/IFabricacionService/InsertarLoteResponse")]
        int InsertarLote(string nroLote, int idTipoLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/InsertarLote", ReplyAction="http://tempuri.org/IFabricacionService/InsertarLoteResponse")]
        System.Threading.Tasks.Task<int> InsertarLoteAsync(string nroLote, int idTipoLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/EditarLote", ReplyAction="http://tempuri.org/IFabricacionService/EditarLoteResponse")]
        bool EditarLote(int idLote, string nroLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/EditarLote", ReplyAction="http://tempuri.org/IFabricacionService/EditarLoteResponse")]
        System.Threading.Tasks.Task<bool> EditarLoteAsync(int idLote, string nroLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/EliminarLote", ReplyAction="http://tempuri.org/IFabricacionService/EliminarLoteResponse")]
        bool EliminarLote(int idLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/EliminarLote", ReplyAction="http://tempuri.org/IFabricacionService/EliminarLoteResponse")]
        System.Threading.Tasks.Task<bool> EliminarLoteAsync(int idLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/ListaLotes", ReplyAction="http://tempuri.org/IFabricacionService/ListaLotesResponse")]
        ETNA.MVC.FabricacionServices.LoteDto[] ListaLotes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricacionService/ListaLotes", ReplyAction="http://tempuri.org/IFabricacionService/ListaLotesResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.FabricacionServices.LoteDto[]> ListaLotesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFabricacionServiceChannel : ETNA.MVC.FabricacionServices.IFabricacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FabricacionServiceClient : System.ServiceModel.ClientBase<ETNA.MVC.FabricacionServices.IFabricacionService>, ETNA.MVC.FabricacionServices.IFabricacionService {
        
        public FabricacionServiceClient() {
        }
        
        public FabricacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FabricacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ETNA.MVC.FabricacionServices.TB_PR_SolicitudProduccion[] TB_PR_SolicitudProduccion_Listar(string pCOD_ESTADO) {
            return base.Channel.TB_PR_SolicitudProduccion_Listar(pCOD_ESTADO);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FabricacionServices.TB_PR_SolicitudProduccion[]> TB_PR_SolicitudProduccion_ListarAsync(string pCOD_ESTADO) {
            return base.Channel.TB_PR_SolicitudProduccion_ListarAsync(pCOD_ESTADO);
        }
        
        public int InsertarLote(string nroLote, int idTipoLote) {
            return base.Channel.InsertarLote(nroLote, idTipoLote);
        }
        
        public System.Threading.Tasks.Task<int> InsertarLoteAsync(string nroLote, int idTipoLote) {
            return base.Channel.InsertarLoteAsync(nroLote, idTipoLote);
        }
        
        public bool EditarLote(int idLote, string nroLote) {
            return base.Channel.EditarLote(idLote, nroLote);
        }
        
        public System.Threading.Tasks.Task<bool> EditarLoteAsync(int idLote, string nroLote) {
            return base.Channel.EditarLoteAsync(idLote, nroLote);
        }
        
        public bool EliminarLote(int idLote) {
            return base.Channel.EliminarLote(idLote);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarLoteAsync(int idLote) {
            return base.Channel.EliminarLoteAsync(idLote);
        }
        
        public ETNA.MVC.FabricacionServices.LoteDto[] ListaLotes() {
            return base.Channel.ListaLotes();
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.FabricacionServices.LoteDto[]> ListaLotesAsync() {
            return base.Channel.ListaLotesAsync();
        }
    }
}
